#! /bin/bash

ret=0
ERR_DKMS_ADD=16
ERR_DKMS_BUILD=17
ERR_DKMS_INSTALL=18
ERR_DKMS_MOD_NAME=19
ERR_DKMS_MOD_VERSION=20
ERR_DKMS_REMOVE=21

# Deb packaging scons target modifies the below fields
DKMS_MODULE_NAME=""
DKMS_MODULE_VERSION=""

if [ "$DKMS_MODULE_NAME" = "" ]; then
    echo "DKMS_MODULE_NAME must be specified."
    ret=$ERR_DKMS_MOD_NAME
fi

if [ "$DKMS_MODULE_VERSION" = "" ]; then
    echo "DKMS_MODULE_VERSION must be specified."
    ret=$ERR_DKMS_MOD_VERSION
fi

print_heading() {
    echo "======== $1 ========"
}

process_dkms() {
    print_heading "Processing DKMS"
    dkms add -m "$DKMS_MODULE_NAME" -v "$DKMS_MODULE_VERSION"
    ret=$?
    if [ $ret -ne 0 ]; then
        ret=$ERR_DKMS_ADD
    else
        kernel_count=0
        for sm in `find /boot -nowarn -name "System.map*"`; do
            kernel=${sm#"/boot/System.map-"}
            grep -wq quirk_nfp6000 $sm
            if [ $? -ne 0 ]; then
                echo -n "ERR47 kernel patches not detected for version: "
                echo $kernel
                # TODO: instruct the user on how to apply them
            else
                echo -n $sm
                echo " has ERR47 patch"
                dkms build -m "$DKMS_MODULE_NAME" -v "$DKMS_MODULE_VERSION" \
                    -k $kernel
                ret=$?
                if [ $ret -ne 0 ]; then
                    ret=$ERR_DKMS_BUILD
                    # NIC-305 Rollback changes when anything fails here
                    dkms remove -m "$DKMS_MODULE_NAME" -v "$DKMS_MODULE_VERSION"
                else
                    dkms install -m "$DKMS_MODULE_NAME" -v \
                        "$DKMS_MODULE_VERSION" -k $kernel
                    ret=$?
                    if [ $ret -ne 0 ]; then
                        ret=$ERR_DKMS_INSTALL
                        # NIC-305 Rollback changes when anything fails here
                        dkms remove -m "$DKMS_MODULE_NAME" -v "$DKMS_MODULE_VERSION"
                    fi
                    kernel_array[kernel_count]=$kernel
                    let "kernel_count= $kernel_count + 1"
                fi
            fi
        done

   fi
}

echo "Executing the Post install script"

FIRMWARE_DIR=/lib/firmware/netronome
# CNIC is from deb/rpm and UPNIC is upstream FW or backup of
FIRMWARE_DIR_CNIC=/lib/firmware/netronome/cnic
FIRMWARE_DIR_UPNIC=/lib/firmware/netronome/nic

mkdir -p $FIRMWARE_DIR_CNIC
mkdir -p $FIRMWARE_DIR_UPNIC

#Delete symbolic links if any
find $FIRMWARE_DIR -maxdepth 1 -name *.nffw -type l -delete

#Delete hard links if any
for FILE in `find $FIRMWARE_DIR -maxdepth 1 -type f -name *.nffw`; do
    if [ $(stat --printf='%h' $FILE) != '1' ]; then
        rm $FILE
    fi
done

# backup remaining FW files, assumed to be upstream FW
# TODO: figure out what to do with future upstream FW already placed in UPNIC
find $FIRMWARE_DIR -maxdepth 1 -type f -name *.nffw -exec mv -t \
    $FIRMWARE_DIR_UPNIC {} +;

# Create symlinks to the just copied FW on FIRMWARE_DIR for the driver to use
find $FIRMWARE_DIR_CNIC -maxdepth 1 -name '*.nffw' -exec ln -s {} $FIRMWARE_DIR \;

process_dkms
if [ $ret -ne 0 ]; then
    echo "There was an error processing dkms install. ERROR $ret"
fi

# Backup netronome blacklist
blacklist_file=/etc/modprobe.d/blacklist-netronome.conf

if [ -e "$blacklist_file" ]; then
    cp "$blacklist_file" "$blacklist_file".corenic.bak
fi

# Enable start script
if `readlink /proc/1/exe | grep -qi systemd`; then
    systemctl enable ns-core-nic.service
else
    update-rc.d ns-core-nic.autorun defaults
    update-rc.d ns-core-nic.autorun enable
fi

# update initramfs
update-initramfs -uk $(uname -r)

# Clear any old config
/opt/netronome/bin/ns-core-nic-setup clean

# Generate new config
/opt/netronome/bin/ns-core-nic-setup force

# Disable logging
/opt/netronome/bin/ns-core-nic-setup log-disable

echo "Core NIC's nfp driver succesfully installed for the following"
echo "kernel versions:"
echo -n -e "\t"
count=0
while [ $count -lt $kernel_count ]; do
    echo -n ${kernel_array[${count}]}
    echo -n " "
    count=$(( $count + 1 ))
done
echo ""

/opt/netronome/bin/ns-core-nic-setup check-flash || :
