#! /bin/bash

# remove nfp driver from dkms
dkms status | while read line[i];
    do
        if ( [[ ${line} == *"nfp"* ]] || [[ ${line} == *"nfp-net"* ]] );then
            nfp_net_name=$(echo $line | cut -d "," -f 1)
            nfp_net_ver=$(echo $line | cut -d "," -f 2)
            kernel_ver=$(echo $line | cut -d "," -f 3)
            dkms remove -m  $nfp_net_name -v $nfp_net_ver -k $kernel_ver
        fi
    done


blacklist_file=/etc/modprobe.d/blacklist-netronome.conf

# restore netronome blacklist file
if [ -e "$blacklist_file".corenic.bak ]; then
    cp "$blacklist_file".corenic.bak "$blacklist_file"
    rm "$blacklist_file".corenic.bak
fi

if `readlink /proc/1/exe | grep -qi systemd`; then
    systemctl stop ns-core-nic.service
    systemctl disable ns-core-nic.service
else
    # Delete udev rules, modprobe blacklist, and firmware files
    service ns-core-nic.autorun clean

    # disable autostart
    update-rc.d ns-core-nic.autorun disable

    # remove start script
    update-rc.d -f ns-core-nic.autorun remove
fi
