#a Copyright (C) 2015,  Gavin J Stark.  All rights reserved.
#
# @file        firmware/Makefile.apps
# @brief       Makefile for the individual apps
#

include $(FIRMWARE_DIR)/apps/nic/Makefile
include $(FIRMWARE_DIR)/apps/vrouter/Makefile
